services:
  voilaaccount_postgres_connector:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.postgres_connector
    environment:
      CONNECTION_URI: $VOILAACCOUNT_POSTGRES_CONNECTOR_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $VOILAACCOUNT_POSTGRES_CONNECTOR_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $VOILAACCOUNT_POSTGRES_CONNECTOR_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $VOILAACCOUNT_POSTGRES_CONNECTOR_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - mode: ingress
        protocol: tcp
        published: "4902"
        target: 8080
